#pragma once
// ============================================================================
// DDS bootstrap helpers: everything in the system is created from NAMED
// profiles in qos/radar_qos.xml (single QoS file, per design).
//
//   auto participant = radds::make_participant(domain, profile, "Radar.X");
//   auto topic       = radds::make_topic<T>(participant, name, profile);
//   auto writer      = radds::make_writer<T>(publisher, topic, profile);
//   auto reader      = radds::make_reader<T>(subscriber, topic, profile);
//
// Participant names ("Radar.BeamScheduler", "TargetGen.Generator", ...) are
// applied programmatically so each component shows up individually in
// Connext Studio's topology map.
// ============================================================================

#include <cstdlib>
#include <filesystem>
#include <stdexcept>
#include <string>

#if defined(_WIN32)
#  include <windows.h>
#elif defined(__APPLE__)
#  include <mach-o/dyld.h>
#elif defined(__linux__)
#  include <unistd.h>
#endif

#include <dds/core/ddscore.hpp>
#include <dds/domain/ddsdomain.hpp>
#include <dds/pub/ddspub.hpp>
#include <dds/sub/ddssub.hpp>
#include <rti/core/policy/CorePolicy.hpp>

#include "radar_types.hpp" // generated by rtiddsgen from idl/radar_types.idl

namespace radds {

inline std::filesystem::path executable_directory() {
#if defined(_WIN32)
    std::wstring buffer(32768, L'\0');
    const DWORD length = GetModuleFileNameW(
        nullptr, buffer.data(), static_cast<DWORD>(buffer.size()));
    if (length == 0 || length == buffer.size())
        return {};
    buffer.resize(length);
    return std::filesystem::path(buffer).parent_path();
#elif defined(__APPLE__)
    uint32_t size = 0;
    (void)_NSGetExecutablePath(nullptr, &size);
    std::string buffer(size, '\0');
    if (_NSGetExecutablePath(buffer.data(), &size) != 0)
        return {};
    return std::filesystem::weakly_canonical(buffer).parent_path();
#elif defined(__linux__)
    std::error_code ec;
    const auto executable = std::filesystem::read_symlink("/proc/self/exe", ec);
    return ec ? std::filesystem::path{} : executable.parent_path();
#else
    return {};
#endif
}

// Resolve the QoS file: $RADAR_QOS_FILE overrides; otherwise look for
// "qos/radar_qos.xml" relative to CWD, then next to the executable tree.
// Note: QosProvider accepts plain paths in its URL group; do NOT prefix
// with "file:" (a single-slash file: URI fails to load).
inline std::string qos_file_uri() {
    if (const char* env = std::getenv("RADAR_QOS_FILE"))
        return env;
    const auto executable_dir = executable_directory();
    const std::filesystem::path candidates[] = {
        "qos/radar_qos.xml",
        "../qos/radar_qos.xml",
        executable_dir / "qos/radar_qos.xml",
        executable_dir / "../qos/radar_qos.xml"
    };
    for (const auto& candidate : candidates) {
        if (!candidate.empty() && std::filesystem::exists(candidate))
            return std::filesystem::absolute(candidate).lexically_normal().string();
    }
    throw std::runtime_error(
        "qos/radar_qos.xml not found; set RADAR_QOS_FILE to its path");
}

inline dds::core::QosProvider& qos_provider() {
    static dds::core::QosProvider provider(qos_file_uri());
    return provider;
}

// Disable RTI Monitoring Library 2.0 for this process. In Connext 7.7 it
// is AUTO-ENABLED by default on the shared libs (librtimonitoring2 ships
// in the target lib dir): every process spawned a monitoring participant
// and flooded Connext Studio's System Visualization with
// rti/dds/monitoring/* topics. This project uses ddsspy for data
// inspection instead. Call FIRST in main(): the setting lives on the
// DomainParticipantFactory singleton, which our XML QosProvider cannot
// reach (it only carries entity profiles). The RTI_MONITORING2_ENABLE
// env var takes precedence if set.
inline void disable_monitoring_lib() {
    auto fqos = dds::domain::DomainParticipant::participant_factory_qos();
    fqos << rti::core::policy::Monitoring::Disabled();
    dds::domain::DomainParticipant::participant_factory_qos(fqos);
}

inline dds::domain::DomainParticipant make_participant(
        int32_t domain_id,
        const std::string& participant_profile,
        const std::string& entity_name) {
    auto pqos = qos_provider().participant_qos(participant_profile);
    // Descriptive entity name -> Connext Studio topology map label
    pqos << rti::core::policy::EntityName(entity_name);
    dds::domain::DomainParticipant participant(domain_id, pqos);
    return participant;
}

template <typename T>
dds::topic::Topic<T> make_topic(
        const dds::domain::DomainParticipant& participant,
        const std::string& topic_name) {
    return dds::topic::Topic<T>(participant, topic_name);
}

template <typename T>
dds::pub::DataWriter<T> make_writer(
        const dds::pub::Publisher& publisher,
        const dds::topic::Topic<T>& topic,
        const std::string& profile) {
    auto wqos = qos_provider().datawriter_qos(profile);
    return dds::pub::DataWriter<T>(publisher, topic, wqos);
}

template <typename T>
dds::sub::DataReader<T> make_reader(
        const dds::sub::Subscriber& subscriber,
        const dds::topic::Topic<T>& topic,
        const std::string& profile) {
    auto rqos = qos_provider().datareader_qos(profile);
    return dds::sub::DataReader<T>(subscriber, topic, rqos);
}

} // namespace radds
