#pragma once
// ============================================================================
// DDS bootstrap helpers: everything in the system is created from NAMED
// profiles in qos/radar_qos.xml (single QoS file, per design).
//
//   auto participant = radds::make_participant(domain, profile, "Radar.X");
//   auto topic       = radds::make_topic<T>(participant, name, profile);
//   auto writer      = radds::make_writer<T>(publisher, topic, profile);
//   auto reader      = radds::make_reader<T>(subscriber, topic, profile);
//
// Participant names ("Radar.BeamScheduler", "TargetGen.Generator", ...) are
// applied programmatically so each component shows up individually in
// Connext Studio's topology map.
// ============================================================================

#include <cstdlib>
#include <filesystem>
#include <stdexcept>
#include <string>

#include <dds/core/ddscore.hpp>
#include <dds/domain/ddsdomain.hpp>
#include <dds/pub/ddspub.hpp>
#include <dds/sub/ddssub.hpp>
#include <rti/core/policy/CorePolicy.hpp>

#include "radar_types.hpp" // generated by rtiddsgen from idl/radar_types.idl

namespace radds {

// Resolve the QoS file: $RADAR_QOS_FILE overrides; otherwise look for
// "qos/radar_qos.xml" relative to CWD, then next to the executable tree.
// Note: QosProvider accepts plain paths in its URL group; do NOT prefix
// with "file:" (a single-slash file: URI fails to load).
inline std::string qos_file_uri() {
    if (const char* env = std::getenv("RADAR_QOS_FILE"))
        return env;
    const std::filesystem::path rel = "qos/radar_qos.xml";
    if (std::filesystem::exists(rel))
        return std::filesystem::absolute(rel).string();
    const std::filesystem::path alt = "../qos/radar_qos.xml";
    if (std::filesystem::exists(alt))
        return std::filesystem::absolute(alt).string();
    throw std::runtime_error(
        "qos/radar_qos.xml not found; set RADAR_QOS_FILE to its path");
}

inline dds::core::QosProvider& qos_provider() {
    static dds::core::QosProvider provider(qos_file_uri());
    return provider;
}

inline dds::domain::DomainParticipant make_participant(
        int32_t domain_id,
        const std::string& participant_profile,
        const std::string& entity_name) {
    auto pqos = qos_provider().participant_qos(participant_profile);
    // Descriptive entity name -> Connext Studio topology map label
    pqos << rti::core::policy::EntityName(entity_name);
    dds::domain::DomainParticipant participant(domain_id, pqos);
    return participant;
}

template <typename T>
dds::topic::Topic<T> make_topic(
        const dds::domain::DomainParticipant& participant,
        const std::string& topic_name) {
    return dds::topic::Topic<T>(participant, topic_name);
}

template <typename T>
dds::pub::DataWriter<T> make_writer(
        const dds::pub::Publisher& publisher,
        const dds::topic::Topic<T>& topic,
        const std::string& profile) {
    auto wqos = qos_provider().datawriter_qos(profile);
    return dds::pub::DataWriter<T>(publisher, topic, wqos);
}

template <typename T>
dds::sub::DataReader<T> make_reader(
        const dds::sub::Subscriber& subscriber,
        const dds::topic::Topic<T>& topic,
        const std::string& profile) {
    auto rqos = qos_provider().datareader_qos(profile);
    return dds::sub::DataReader<T>(subscriber, topic, rqos);
}

} // namespace radds
